import { z } from "zod";
import { professionalCompletion } from "@/lib/professional-completeness";

export const createProfessionalSchema = z.object({
  displayName: z.string().min(2),
  bio: z.string().optional().default(""),
  city: z.string().min(2),
  state: z.string().min(2),
  bairro: z.string().trim().min(2).optional(),
  region: z.string().trim().min(2).optional(),
  address: z.string().optional(),
  placeId: z.string().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  phone: z.string().optional(),
  whatsapp: z.string().optional(),
  instagram: z.string().optional(),
  website: z.string().optional(),
  priceMin: z.number().positive().optional(),
  priceMax: z.number().positive().optional(),
  price15min: z.number().positive().optional(),
  pricePerHour: z.number().positive().optional(),
  price30min: z.number().positive().optional(),
  price2h: z.number().positive().optional(),
  priceOvernight: z.number().positive().optional(),
  priceWebcam: z.number().positive().optional(),
  paymentMethods: z.array(z.string()).optional().default([]),
  escortCategory: z.string().optional(),
  birthDate: z.string().optional(),
  height: z.number().optional(),
  weight: z.number().optional(),
  hairColor: z.string().optional(),
  eyeColor: z.string().optional(),
  ethnicity: z.string().optional(),
  signo: z.string().optional(),
  hasTattoos: z.boolean().optional().default(false),
  hasPiercing: z.boolean().optional().default(false),
    hasSilicone: z.boolean().optional().default(false),
  smoker: z.boolean().optional().default(false),
  isDepilada: z.boolean().optional().default(true),
  depilationStyle: z.string().optional(),
  bodyType: z.string().optional(),
  attendanceTypes: z.array(z.string()).optional().default([]),
  servesGenders: z.array(z.string()).optional().default([]),
  idiomas: z.array(z.string()).optional().default([]),
  diasDisponiveis: z.array(z.string()).optional().default([]),
  horarioInicio: z.string().optional(),
  horarioFim: z.string().optional(),
  specialties: z.array(z.string()).optional().default([]),
  services: z.array(z.string()).optional().default([]),
  servicesNotOffered: z.array(z.string()).optional().default([]),
  fetishes: z.array(z.string()).optional().default([]),
  amenities: z.array(z.string()).optional().default([]),
  serviceCities: z.array(z.string()).optional().default([]),
  approximateLocation: z.string().max(160).optional(),
  image: z.string().optional(),
  galleryUrls: z.array(z.string()).optional().default([]),
  docType: z.string().optional(),
  docFrenteUrl: z.string().optional(),
  docVersoUrl: z.string().optional(),
  docStatus: z.string().optional().default("PENDING"),
  verifStatus: z.string().optional().default("PENDING"),
  verificationUrl: z.string().optional(),
  verificationType: z.string().optional(),
  verificationCode: z.string().optional(),
  kycProvider: z.string().optional(),
  kycSessionId: z.string().optional(),
  kycStatus: z.string().optional(),
}).superRefine((data, ctx) => {
  const result = professionalCompletion({
    ...data,
    image: data.image,
    emailVerified: true,
  });
  for (const issue of result.profileIssues) {
    ctx.addIssue({ code: "custom", path: [issue.field], message: issue.label });
  }
  if (!data.kycSessionId) {
    ctx.addIssue({ code: "custom", path: ["kycSessionId"], message: "Verificação de identidade não iniciada" });
  }
});
